"""
This module captures constants used across the codebase.
"""
MODELS = ["CM", "CM3x3", "CN", "CN3x3", "CSD", "GLRLM", "GLRLM3x3", "HOG", "LBP", "LBP3x3"]
MODELS_6A = ["CM", "CN", "CSD", "GLRLM", "HOG", "LBP"]
PROCESSED_VISUAL_DESCRIPTORS_DIR_PATH = "../dataset/visual_descriptors/processed/"
VISUAL_DESCRIPTORS_DIR_PATH_REGEX = "../dataset/visual_descriptors/*.csv"
DEVSET_TOPICS_DIR_PATH = "../dataset/textual_descriptors/devset_topics.xml"
VISUAL_DESCRIPTORS_DIR_PATH = "../dataset/visual_descriptors/"
TEXT_DESCRIPTORS_DIR_PATH = "../dataset/textual_descriptors/"
DUMPED_OBJECTS_DIR_PATH = "../dumped_objects/"
LOCATION_ID_KEY_ERROR = "Wrong input: Location id not found"
GENERIC_EXCEPTION_MESSAGE = "Exception encountered: "
VISUAL_DESCRIPTOR_MODEL_FOR_GRAPH_CREATION = "CN"
VISUALIZATIONS_DIR_PATH = "../visualizations/"
GRAPH_FILE = "../visualizations/reduced_graph_file.txt"
ENTIRE_GRAPH_FILE = "../visualizations/entire_graph_file.txt"
VISUALIZATIONS_GRAPH_FILE = "../visualizations/visualisation_graph_file.txt"
TASK1_OUTPUT_FILE = "../output/task1_output_file.txt"
TASK2a_OUTPUT_FILE = "../output/task2a_output_file.txt"
TASK2b_OUTPUT_FILE = "../output/task2b_output_file.txt"
TASK3_OUTPUT_FILE = "../output/task3_output.txt"
TASK3b_OUTPUT_FILE = "../output/task3b_output.txt"
TASK4_OUTPUT_FILE = "../output/task4_output.txt"
TASK4NX_OUTPUT_FILE = "../output/task4nx_output.txt"
TASK5_OUTPUT_FILE = "../output/task5_output.txt"
TASK6a_OUTPUT_FILE = "../output/task6a_output.txt"
TASK6b_OUTPUT_FILE = "../output/task6b_output.txt"
TASK6_INPUT_FILE1 = "./PPR_input1.txt"
TASK6_INPUT_FILE2 = "./PPR_input2.txt"